### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by evanslify** [JakubOnderka/api-blueprint-validator#13]
On node v6.2.2 and api-blueprint-validator 0.1.3:

```
$ ./node_modules/.bin/api-blueprint-validator ./api.md
./node_modules/.store/api-blueprint-validator@0.1.3/_/src/validator.js:74
      result.warnings.forEach(function (warning) {
                     ^

TypeError: Cannot read property 'forEach' of undefined
    at ./node_modules/.store/api-blueprint-validator@0.1.3/_/src/validator.js:74:22
```

**Comment by anentropic** [comment]
same here

**Comment by mifkamaz** [comment]
+

**Comment by eiwi1101** [comment]
+

```
/Users/.../.../node_modules/api-blueprint-validator/src/validator.js:74
      result.warnings.forEach(function (warning) {
                     ^

TypeError: Cannot read property 'forEach' of undefined
    at /Users/.../.../node_modules/api-blueprint-validator/src/validator.js:74:22
```

Node: v5.12.0
api-blueprint-validator: 0.1.3

**Comment by eiwi1101** [comment]
See pull #6 for a branch that patches this issue. That pull has been open since September '15, so stale bread. :goat:

**Comment by aswinjoseroy** [comment]
same here, can't you merge the fix to master?

**Comment by cherehapa** [comment]
looks like pull request #10 makes #6  obsolette and should be better solution, at least we've problems building old protagonist on Ubuntu 14.04 - failing w/ node-gyo rebuild (latest pass this if we remove ubuntu node-gyp and install it via npm -g  .

**Comment by cherehapa** [comment]
finally we merged all fixing pullrequests into our one + implemented json schema checks - see pullrequest #16
